CREATE OR REPLACE SERVER control_room_server 
FOREIGN DATA WRAPPER mysql
OPTIONS (
  HOST '<HOST>',
  DATABASE '<DB_NAME>',
  USER '<DB_USER>',
  PASSWORD '<DB_PASSWORD>'
);
-- Login DB
CREATE OR REPLACE SERVER login_server
FOREIGN DATA WRAPPER mysql
OPTIONS (
  HOST '<HOST>',
  DATABASE '<DB_NAME>',
  USER '<DB_USER>',
  PASSWORD '<DB_PASSWORD>'
);