# This is a basic workflow to help you get started with Actions

name: Migrate sql file

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  # push:
  #   branches: [ "dev" ]
  # pull_request:
  #   branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      folder:
        description: 'path to folder'
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: '${{ github.ref_name }}' # This is the environment name
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # get database credentials from secrets
      - name: Get database credentials
        run: |
          echo "Branch name: ${{ github.ref_name }}"
          echo "DB_HOST=$DB_HOST" >> $secrets.DB_HOST
          echo "DB_USER=$DB_USER" >> $secrets.DB_USER
          echo "DB_PASS=$DB_PASS" >> $secrets.DB_PASS
          echo "DB_NAME=$DB_NAME" >> $secrets.DB_NAME

      - name: Make shell script executable
        run: |
          pwd
          ls -la
          chmod +x migration.sh
      
      - name: Run shell script
        run: |
          ./migration.sh ${{ github.event.inputs.folder }}
